export enum ErrorCode {
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    INVALID_REQUEST = "INVALID_REQUEST",
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    PERMISSION_DENIED = "PERMISSION_DENIED",
    SERIALIZATION_FAILURE = "SERIALIZATION_FAILURE",
    INVALID_PAYLOAD_FORMAT = "INVALID_PAYLOAD_FORMAT",
    MISSING_AUTH_KEY = "MISSING_AUTH_KEY",
    INVALID_OR_EXPIRED_AUTH_KEY = "INVALID_OR_EXPIRED_AUTH_KEY",
}

